### ISSUE TITLE
Extend command timeout?

### ISSUE THREAD

**Issue by tonygomez** [ccrookston/Dapper.SimpleRepository#2]
How would I extend the timeout using this method?

 Task<IEnumerable<T>> GetListFromQueryAsync<T>(
      string query,
      Dictionary<string, object> parms = null);

Thanks!

**Comment by ccrookston** [comment]
That is a really good idea!  I’ll make it happen.

**Comment by ccrookston** [comment]
Hey Tony,

I didn’t give a very good response the first time. Let me look into
time-out settings for Dapper and get back to you.

Casey

**Comment by tonygomez** [comment]
@ccrookston thank you for your help and the fast response!

**Comment by ccrookston** [comment]
Hey Tony,

Ok, I must be getting rusty. I had to go look this up!  The answer to your
question is: You can set the timeout value in your connection string.  For
example:

string connStr = "Data Source=(local);Initial
Catalog=AdventureWorks;Integrated Security=SSPI;Connection
Timeout=30";

**Comment by tonygomez** [comment]
@ccrookston thanks for the suggestion. I was hoping not extend the timeout for the entire application via the connection string.  Dapper has a few overloads which allow you to extent the timeout for that one query.  If this cannot be added at this time no problem. I greatly appreciated your excellent work in simple repository and try and carve out some time to create a PR.

Thanks!

**Comment by ccrookston** [comment]
Hey Tony,

I am going to spend a little time adding overloads for command timeout. It
may be around the middle of January before I can publish it. In the
meantime, if you don't want the entire app to use a connection with a
longer timeout, you can add a second connection with that timeout and use
it when you need it. I know. It's a workaround :)

I'll let you know when the new version is ready.

Casey

**Comment by ccrookston** [comment]
Actually, that went faster than I thought it would. A new version is out
that has optional Command Time Out parameters for all of the methods that
support it in Dapper.  Thank you for encouraging me to do this.

**Comment by tonygomez** [comment]
@ccrookston Fantastic! thank you for the quick response and I look forward to trying it out.
