### ISSUE TITLE
Issue inserting with Guid id.

### ISSUE THREAD

**Issue by GusBeare** [ccrookston/Dapper.SimpleRepository#3]
Hi
I really like this project. After a lot of trouble with EF I've come back to Dapper and found this and what a pleasure it is to use! Thank you.  However, I do have an issue.  When I try to insert a row with a Guid id I get this error.

    'Unable to cast object of type 'System.Guid' to type 'System.IConvertible'.'

I am using strongly typed repo. Code like this:

     public class Franchise
      {
          [Key]
          public Guid Guid { get; set; }
          public string Name { get; set; }
          public Guid CreatedBy { get; set; }
          public DateTime Created { get; set; }
          public Guid? ModifiedBy { get; set; }
          public DateTime? Modified { get; set; }
  
       }

       private readonly IRepositoryStrong<Models.Franchise> repo = new Repository<Models.Franchise>(Startup.TestConnection);

       FranchiseForm.Guid = Guid.NewGuid();
       FranchiseForm.Created = DateTime.Now;
       FranchiseForm.CreatedBy = userGuid;
       repo.Insert(FranchiseForm);

Is there something I am doing wrong?

thanks
Gus

**Comment by ccrookston** [comment]
Hi Gus,

Thanks for reaching out! Off the top of my head, the problem is probably
that your GUID is also a Key? I think it's expecting the primary key to be
an int. I may need to add an overload method for a non-integer key. I am
not sure when I can get to that... most likely later this week. In the
meantime, if you want to propose a solution, feel free to let me know.

Thanks!

Casey

**Comment by GusBeare** [comment]
Hi Casey,
Thanks for responding.
Yes. The table has a Guid PK.  I am in the habit of using them because of merge replication and disconnected apps where data is collected offline and then uploaded later.  I am often surprised that int Id's are the default when Guid's offer such useful advantages. I like being able to generate a unique Id for a row without asking the DB for it.  I've worked with cms applications where Id's are used and you need developers working on a dev site adding pages and modules. When it comes to merging their work with the live system (where users have been adding pages)  you are in trouble since you have Id conflicts.

At the moment I am prototyping an app for a project and trying to decide what to use for the db stuff. I initially thought I'd go with EF Core because it's used by Identity out of the box. BUT, I prefer to build out the DB by hand and I found all the Db First scaffolding  a headache.  Plus the form scaffolding is not for me because I prefer modal edits with ajax instead of page posts. Then I had to customise everything because (you guessed it) EF defaults to Id Pk's!

It was a breath of fresh air to go back to Dapper and find SimpleRepository. I was where I wanted to be in minutes .

Not being able to handle Guid PK's is a show stopper for me so I'd appreciate a fix later this week. I don't think I have the knowledge to suggest an alternative fix unfortunately but an overload would be great.

cheers
Gus

**Comment by ccrookston** [comment]
Hey Gus,

v1.1.1 is now available. Release notes:  Allow for the possibility that
Primary Keys may be an object type other than Int. (Examples: Guid, string,
uint, long, ulong, short, ushort)

To take advantage, simply make this change:

   FranchiseForm.Guid = Guid.NewGuid();
   FranchiseForm.Created = DateTime.Now;
   FranchiseForm.CreatedBy = userGuid;
   repo.Insert<Guid>(FranchiseForm);

I've also adjusted the GET and DELETE commands to work as well. Let me know
how it works!

Casey

**Comment by ccrookston** [comment]
Small correction. It changed the version to 1.2.0

**Comment by GusBeare** [comment]
thanks Casey.
Unfortunately I can't get INSERT to work. I've upgraded to 1.2.0.
It expects a Guid where the POCO is.

![Capture](https://user-images.githubusercontent.com/5166509/132762933-00229d20-5ac3-4847-b50f-c197db5fba3e.JPG)

**Comment by GusBeare** [comment]
Never mind. I wasn't using a strongly type repo. Works fine thanks!

**Comment by ccrookston** [comment]
Hey Gus,

Glad to hear it's working! That being said, it *should* work either way. I
tested with both an Int and a Guid as the primary key using the following:

   - Non-Strongly Typed Async
   - Non-Strongly Typed Non-Async
   - Strongly Typed Async
   - Strongly Typed Non-Async

The INSERTS for each would look like this:

Non-Strongly Typed:

Guid guidResult = await _repoGeneric.InsertAsync<Guid, ModeClassl>(model);
Guid guidResult = _repoGeneric.Insert<Guid,  ModeClassl>(model);


Strongly Typed:

Guid guidResult = await _repoStrong.InsertAsync<Guid>(model);
Guid guidResult = _repoStrong.Insert<Guid>(model);

But again, I'm glad it's working! I'll go ahead and mark this issue as
resolved.

Casey
