### ISSUE TITLE
Sqlite sample

### ISSUE THREAD

**Issue by oghenez** [ccrookston/Dapper.SimpleRepository#5]
Hello,

Is this library meant only for sqlserver?
Any ideas on how to make usable for any db?

Regards

**Comment by ccrookston** [comment]
Hello, and thanks for the question. Yes, it is meant only for SQL Server. I
wish I could help you adapt it to other databases but the entire technology
is based on SQL.

Thanks,

Casey

**Comment by oghenez** [comment]
Thanks for your response, i found a way to adapt it to any database!
